import { Injectable } from '@nestjs/common';
import { OrderState } from '@prisma/client';
import { OrderEventType } from './dto/process-order-event.dto';

const EVENT_TARGET_STATE: Record<OrderEventType, OrderState> = {
  ORDER_PLACED: OrderState.ORDER_CREATED,
  PAYMENT_INITIATED: OrderState.PAYMENT_PENDING,
  PAYMENT_SUCCESS: OrderState.PAYMENT_SUCCESS,
  PAYMENT_FAILED: OrderState.PAYMENT_FAILED,
  INVOICE_PENDING: OrderState.INVOICE_PENDING,
  INVOICE_CREATED: OrderState.INVOICE_CREATED,
  OMS_PENDING: OrderState.OMS_PENDING,
  OMS_SUBMITTED: OrderState.OMS_SUBMITTED,
  OMS_SUBMISSION_FAILED: OrderState.OMS_SUBMISSION_FAILED,
  ALLOCATED: OrderState.ALLOCATED,
  UNALLOCATED: OrderState.UNALLOCATED,
  SHIPMENT_PENDING: OrderState.SHIPMENT_PENDING,
  SHIPMENT_CREATED: OrderState.SHIPMENT_CREATED,
  SHIPPED: OrderState.SHIPPED,
  DELIVERED: OrderState.DELIVERED,
  CANCEL_REQUESTED: OrderState.CANCEL_REQUESTED,
  CANCEL_PROCESSING: OrderState.CANCEL_PROCESSING,
  CANCELLED: OrderState.CANCELLED,
  CANCEL_FAILED: OrderState.CANCEL_FAILED,
  REFUND_PENDING: OrderState.REFUND_PENDING,
  REFUND_PROCESSING: OrderState.REFUND_PROCESSING,
  REFUNDED: OrderState.REFUNDED,
  REFUND_FAILED: OrderState.REFUND_FAILED,
};

const ALLOWED_TRANSITIONS: Partial<Record<OrderState, OrderState[]>> = {
  ORDER_CREATED: [OrderState.PAYMENT_PENDING, OrderState.PAYMENT_SUCCESS, OrderState.PAYMENT_FAILED, OrderState.CANCEL_REQUESTED],
  PAYMENT_PENDING: [OrderState.PAYMENT_SUCCESS, OrderState.PAYMENT_FAILED, OrderState.CANCEL_REQUESTED],
  PAYMENT_FAILED: [OrderState.PAYMENT_PENDING, OrderState.PAYMENT_SUCCESS, OrderState.CANCEL_REQUESTED],
  PAYMENT_SUCCESS: [OrderState.INVOICE_PENDING, OrderState.INVOICE_CREATED, OrderState.CANCEL_REQUESTED, OrderState.REFUND_PENDING],
  INVOICE_PENDING: [OrderState.INVOICE_CREATED, OrderState.CANCEL_REQUESTED],
  INVOICE_CREATED: [OrderState.OMS_PENDING, OrderState.OMS_SUBMITTED, OrderState.CANCEL_REQUESTED],
  OMS_PENDING: [OrderState.OMS_SUBMITTED, OrderState.OMS_SUBMISSION_FAILED, OrderState.CANCEL_REQUESTED],
  OMS_SUBMISSION_FAILED: [OrderState.OMS_PENDING, OrderState.OMS_SUBMITTED, OrderState.CANCEL_REQUESTED],
  OMS_SUBMITTED: [OrderState.ALLOCATED, OrderState.UNALLOCATED, OrderState.CANCEL_REQUESTED],
  ALLOCATED: [OrderState.SHIPMENT_PENDING, OrderState.SHIPMENT_CREATED, OrderState.UNALLOCATED, OrderState.CANCEL_REQUESTED],
  UNALLOCATED: [OrderState.ALLOCATED, OrderState.CANCEL_REQUESTED],
  SHIPMENT_PENDING: [OrderState.SHIPMENT_CREATED, OrderState.CANCEL_REQUESTED],
  SHIPMENT_CREATED: [OrderState.SHIPPED, OrderState.CANCEL_REQUESTED],
  SHIPPED: [OrderState.DELIVERED, OrderState.REFUND_PENDING],
  DELIVERED: [OrderState.REFUND_PENDING],
  CANCEL_REQUESTED: [OrderState.CANCEL_PROCESSING, OrderState.CANCELLED, OrderState.CANCEL_FAILED],
  CANCEL_PROCESSING: [OrderState.CANCELLED, OrderState.CANCEL_FAILED],
  CANCEL_FAILED: [OrderState.CANCEL_REQUESTED, OrderState.CANCEL_PROCESSING],
  REFUND_PENDING: [OrderState.REFUND_PROCESSING, OrderState.REFUNDED, OrderState.REFUND_FAILED],
  REFUND_PROCESSING: [OrderState.REFUNDED, OrderState.REFUND_FAILED],
  REFUND_FAILED: [OrderState.REFUND_PENDING, OrderState.REFUND_PROCESSING],
};

@Injectable()
export class OrderStateMachine {
  getTargetState(eventType: OrderEventType): OrderState {
    return EVENT_TARGET_STATE[eventType];
  }

  canTransition(fromState: OrderState, toState: OrderState): boolean {
    return fromState === toState || (ALLOWED_TRANSITIONS[fromState]?.includes(toState) ?? false);
  }
}
